@echo off
echo Starting MarketHub AI Service...
cd ai-service
echo Installing Python dependencies...
pip install -r requirements.txt
echo Starting FastAPI server...
uvicorn app.main:app --reload --port 8086 --host 0.0.0.0
pause
