services:
  catalog-service:
    build:
      context: ../../backend/services/catalog-service
      dockerfile: Dockerfile
    image: markethub/catalog-service:dev
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  ai-service:
    build:
      context: ../../ai-service
      dockerfile: Dockerfile
    image: markethub/ai-service:dev
    ports:
      - "8086:8086"
    restart: unless-stopped

  webapp:
    build:
      context: ../../frontend/webapp-ng
      dockerfile: Dockerfile
    image: markethub/webapp:dev
    ports:
      - "4200:80"
    depends_on:
      - catalog-service
      - ai-service
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=markethub
      - POSTGRES_USER=markethub
      - POSTGRES_PASSWORD=markethub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8082:8080"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  pgdata:
