name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Build catalog-service
        run: mvn -q -DskipTests package -f backend/services/catalog-service/pom.xml

  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai-service/requirements.txt
      - name: Import check
        run: |
          python - <<'PY'
import fastapi, uvicorn, pydantic
print("ok")
PY
