name: Docker Build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build catalog-service image
        run: docker build -t markethub/catalog-service:ci backend/services/catalog-service
      - name: Build ai-service image
        run: docker build -t markethub/ai-service:ci ai-service
      - name: Build webapp image
        run: docker build -t markethub/webapp:ci frontend/webapp
